### ISSUE TITLE
Youtube++ Downloaded videos restarting. 

### ISSUE THREAD

**Issue by blaskotron** [JMccormick264/PPAppsIPARepo#85]
Frequently playing downloading they will go back to 0:00 and start over. 

The downloads are complete and have audio video when skipping ahead. 

I usually download at 144p or audio only. Doesn't seem to matter. 

Screen on or off doesn't seem to matter. 

Using version 1.4r-49 but has occurred in older versions.

**Comment by JMccormick264** [comment]
SHould be fixed.

**Comment by blaskotron** [comment]
Looks like this is still happening after updating. 

1.4r-57.

**Comment by JMccormick264** [comment]
Try updating to the latest https://github.com/JMccormick264/YouTubePP/releases
